### ISSUE TITLE
Is there any plan about upgrade to Python 3.x?

### ISSUE THREAD

**Issue by Qinka** [QTIM-Lab/DeepNeuro#30]
I am looking for full support for python 3.x.

I got some error when run DeepNeuro on python 3.6. (such as https://github.com/QTIM-Lab/DeepNeuro/blob/master/deepneuro/models/callbacks.py#L116). 

The long term support of python 2.7 will stop as a plan in 2020.

**Comment by AndrewBeers** [comment]
Hello Qinka -- thanks for the question.

We also saw that long-term support for 2.7 will stop in 2020 (and probably sooner for individual packages..), and have been working on taking DeepNeuro to 3.x in our latest development branch. We just merged that today, and I think it should solve the errors you've been having.

https://github.com/QTIM-Lab/DeepNeuro/pull/31
