### ISSUE TITLE
Suggestions for Improvement

### ISSUE THREAD

**Issue by changken1** [QTIM-Lab/DeepNeuro#4]
To do:
1) Multi Output Support
-Automatic detection of number of output channels
-Implementation: (number of outputs, x , y, z). Sigmoid activation with binary crossentropy.
2) Additional Augmentation
-Zooming
3) Early stopping based on validation
4) Log file 
5) Continue training

**Comment by AndrewBeers** [comment]
These requests have been addressed in DeepNeuro 0.2
