### ISSUE TITLE
Remove excessive print statements during augmentation phase

### ISSUE THREAD

**Issue by jmbrown89** [QTIM-Lab/DeepNeuro#5]
Lots of repeated print statements like:
_<function roi_region at 0x7fdbdfc9d398>_

 Might be good to have a progress bar of sorts (tqdm, maybe).

**Comment by AndrewBeers** [comment]
Let's replace with tdqm progress bars - working on it soon.

**Comment by AndrewBeers** [comment]
Solved with tdqm!
